const expensesData = [
    {
      id: 1,
      item: "Groceries",
      amount: 150,
      date: "2024-10-02",
      category: "Food",
      description: "Weekly groceries from the supermarket",
    },
    {
      id: 2,
      item: "Rent",
      amount: 1200,
      date: "2024-10-01",
      category: "Housing",
      description: "Monthly rent payment for apartment",
    },
    {
      id: 3,
      item: "Electricity Bill",
      amount: 100,
      date: "2024-09-30",
      category: "Utilities",
      description: "Monthly electricity bill",
    },
    {
      id: 4,
      item: "Gym Membership",
      amount: 50,
      date: "2024-09-25",
      category: "Health",
      description: "Monthly gym membership fee",
    },
    {
      id: 5,
      item: "Internet",
      amount: 60,
      date: "2024-09-20",
      category: "Utilities",
      description: "Monthly internet subscription",
    },
    {
      id: 6,
      item: "Dining Out",
      amount: 75,
      date: "2024-09-18",
      category: "Food",
      description: "Dinner at a restaurant",
    },
    {
      id: 7,
      item: "Fuel",
      amount: 45,
      date: "2024-09-15",
      category: "Transportation",
      description: "Fuel for the car",
    },
    {
      id: 8,
      item: "Streaming Subscription",
      amount: 12,
      date: "2024-09-12",
      category: "Entertainment",
      description: "Monthly streaming service subscription",
    },
    {
      id: 9,
      item: "Phone Bill",
      amount: 35,
      date: "2024-09-10",
      category: "Utilities",
      description: "Monthly phone bill payment",
    },
    {
      id: 10,
      item: "Clothing",
      amount: 200,
      date: "2024-09-05",
      category: "Shopping",
      description: "Purchased new clothes",
    },
  ];
  
export default expensesData;