const incomeData = [
    {
      id: 1,
      source: "Salary",
      amount: 3000,
      date: "2024-10-01",
      description: "Monthly salary for October",
      category: "Job",
    },
    {
      id: 2,
      source: "Freelance Project",
      amount: 1200,
      date: "2024-09-28",
      description: "Payment for website development project",
      category: "Freelance",
    },
    {
      id: 3,
      source: "Stock Dividends",
      amount: 450,
      date: "2024-09-20",
      description: "Quarterly stock dividends from investments",
      category: "Investments",
    },
    {
      id: 4,
      source: "Rental Income",
      amount: 800,
      date: "2024-09-15",
      description: "Monthly rental income for September",
      category: "Real Estate",
    },
    {
      id: 5,
      source: "Consulting",
      amount: 700,
      date: "2024-09-10",
      description: "Consulting work for a tech company",
      category: "Consulting",
    },
    {
      id: 6,
      source: "Interest",
      amount: 50,
      date: "2024-09-05",
      description: "Interest earned from savings account",
      category: "Banking",
    },
    {
      id: 7,
      source: "Bonus",
      amount: 500,
      date: "2024-08-31",
      description: "Quarterly performance bonus",
      category: "Job",
    },
    {
      id: 8,
      source: "Freelance Project",
      amount: 1500,
      date: "2024-08-25",
      description: "Freelance web development for e-commerce site",
      category: "Freelance",
    },
    {
      id: 9,
      source: "Stock Dividends",
      amount: 300,
      date: "2024-08-20",
      description: "Dividends from investment portfolio",
      category: "Investments",
    },
    {
      id: 10,
      source: "Gift",
      amount: 200,
      date: "2024-08-10",
      description: "Birthday gift from family",
      category: "Miscellaneous",
    },
  ];

  export default incomeData;